
/**
 * 默认配置
 */
module.exports = {
    componentType: 'amtype', //提取组件的属性值
    defaultMark: 'div', //默认标签
    event: 2,
    style: 1,
    defaultProperty: 3,
    specialComponents: ['Template','ListView'],
    specialAttributes: ['data','tabs'],
    styleJsx: {
        start: '{{',
        end: '}}'
    },
    var: {
        start: '{',
        end: '}',
        outer: 'this.state.'
    },
    method: {
        start: '{()=>{',
        end: '}}',
        param: '$event',
        outerParam: '{($event)=>{'
    }, 
    prefixStyles: [ //样式转换集合
        'titleStyle',
        'tabBarUnderlineStyle',
        'tabBarTextStyle',
        'containerStyle',
        'textStyle',
        'dotStyle',
        'dotActiveStyle',
        'itemStyle',
        'actionStyle',
        'contentContainerStyle'
    ],
    componentCameProperty: [  //驼峰属性转换后小写问题处理
        'openChange',
        'drawerWidth',
        'multiSelect',
        'rightTitle',
        'rightIcon',
        'showGoBack',
        'showCancel',
        'tabBarPosition',
        'initialPage',
        'tabClick',
        'tabBarBackgroundColor',
        'tabBarActiveTextColor',
        'tabBarInactiveTextColor',
        'barTintColor',
        'tintColor',
        'unselectedTintColor',
        'selectedTab',
        'marginTop',
        'selectedIcon',
        'minDate',
        'maxDate',
        'startDate',
        'endDate',
        'fontSize',
        'fontColor',
        'minuteStep',
        'valueChange',
        'loadingUrl',
        'failUrl',
        'resizeMode',
        'defaultValue',
        'maxLength',
        'errorClick',	
        'extraClick',
        'labelClick',
        'labelNumber',
        'labelIcon',
        'fontWeight',
        'textAlign',
        'pickerChange',
        'okText',
        'dismissText',
        'showCancelButton',
        'cancelText',
        'spaceAfter',
        'backgroundColor',
        'isRandom',
        'showLevel',
        'readOnly',
        'autoHeight',
        'selectedIndex',
        'autoplayInterval',
        'afterChange',
        'columnNum',
        'hasLine',
        'isCarousel',
        'carouselMaxRow',
        'imgWidth',
        'imgHeight',
        'marqueeProps',
        'actionText',
        'afterClose',
        'downRefresh',
        'upRefresh',
        'numColumns'
    ],
    componentMethods: [ //事件处理
        'openChange',
        'change',
        'ok',
        'cancel',
        'back',
        'right',
        'tabClick',
        'press',
        'click',
        'confirm',
        'valueChange',
        'init',
        'dismiss',
        'blur',
        'focus',
        'errorClick',
        'extraClick',
        'labelClick',
        'pickerChange',
        'afterChange',
        'afterClose',
        'downRefresh',
        'upRefresh'
    ]
}